### ISSUE TITLE
I cannot install this plugin. Error in gzipgile?

### ISSUE THREAD

**Issue by rmarabini** [scipion-em/scipion-em-spider#4]
If I try to install spider I get the error:

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Traceback (most recent call last):
  File "/usr/local/scipion_plugin/install/install-plugin.py", line 203, in <module>
    plugin.installBin(args=['-j', numberProcessor])
  File "/usr/local/scipion_plugin/install/plugin_funcs.py", line 158, in installBin
    environment.execute()
  File "/usr/local/scipion_plugin/install/funcs.py", line 788, in execute
    self._executeTargets(targetList)
  File "/usr/local/scipion_plugin/install/funcs.py", line 726, in _executeTargets
    tgt.execute()
  File "/usr/local/scipion_plugin/install/funcs.py", line 214, in execute
    command.execute()
  File "/usr/local/scipion_plugin/install/funcs.py", line 158, in execute
    "running '%s')" % (t, cmd))
AssertionError: target '/usr/local/scipion_plugin/software/em/spider/spider' not built (after running 'tar -xzf spider-24.03.tgz -C spider')
roberto@Inspiron-3668:/usr/local/scipion_plugin$

**Comment by azazellochg** [comment]
```
>>>>> python  /lmb/home/gsharov/soft/scipion-devel/install/install-plugin.py /lmb/home/gsharov/soft/scipion-devel/scipion installb spider
Building spider-24.03 ...
wget -nv -c -O /lmb/home/gsharov/soft/scipion-devel/software/em/spider-24.03.tgz.part https://spider.wadsworth.org/spider_doc/spider/download/spiderweb.24.03.tar.gz
ERROR: cannot verify spider.wadsworth.org's certificate, issued by ‘/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3’:
  Issued certificate has expired.
To connect to spider.wadsworth.org insecurely, use `--no-check-certificate'.
mv -v /lmb/home/gsharov/soft/scipion-devel/software/em/spider-24.03.tgz.part /lmb/home/gsharov/soft/scipion-devel/software/em/spider-24.03.tgz
‘/lmb/home/gsharov/soft/scipion-devel/software/em/spider-24.03.tgz.part’ -> ‘/lmb/home/gsharov/soft/scipion-devel/software/em/spider-24.03.tgz’
cd /lmb/home/gsharov/soft/scipion-devel/software/em
mkdir /lmb/home/gsharov/soft/scipion-devel/software/em/spider
cd /lmb/home/gsharov/soft/scipion-devel/software/em
tar -xzf spider-24.03.tgz -C spider

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now

```

**Comment by azazellochg** [comment]
ssl/tls certificate for the website expired 3 days ago. The error message tells what you have to do to download it. Plugin / scipion cannot foresee this if the binary is hosted on external website.
